services:
  db:
    image: postgres:16-alpine
    container_name: devpulse-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devpulse
      POSTGRES_PASSWORD: devpulse123
      POSTGRES_DB: devpulse
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
